[build-system]
requires = ["setuptools >= 64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rgevolve.wet-4.jms"
authors = [
    {name = "Aleks SmolkoviÄ", email = "aleks.smolkovic@ijs.si"},
    {name = "Peter Stangl", email = "peter.stangl@cern.ch"},
]
description = "Package providing Renormalization Group Evolution Matrices for the WET-4 in the JMS basis"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "rgevolve"
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src/"]
include = ["rgevolve.wet-4.jms"]

[tool.setuptools.dynamic]
version = {attr = "rgevolve.wet-4.jms._version.__version__"}

[tool.setuptools.package-data]
"rgevolve.wet-4.jms" = ["data.h5"]
